services:
    openapi-generator-cli:
        image: 'openapitools/openapi-generator-cli:v7.0.1'
        volumes:
            - '${TOP_LEVEL_DIR}/:/local'
        working_dir: '/local'

    redocly-cli:
        image: 'redocly/cli'
        volumes:
            - '${TOP_LEVEL_DIR}/:/spec'

    spectral:
        image: 'stoplight/spectral'
        volumes:
            - '${TOP_LEVEL_DIR}/:/tmp'
        working_dir: '/tmp'
