services:
    openapi-generator-cli-php:
        image: 'openapitools/openapi-generator-cli:v7.0.1'
        volumes:
            - '${TOP_LEVEL_DIR}/:/local'
        working_dir: '/local'
        command: generate
            --generator-name php
            --input-spec ${OAS_YAML}
            --output ./openapi/Client

    redocly-cli-build-docs:
        image: 'redocly/cli'
        volumes:
            - '${TOP_LEVEL_DIR}/:/spec'
        # cf. https://redocly.com/docs/cli/commands/build-docs/
        command: build-docs ${OAS_YAML} --output=./public/redocly.html

    spectral-lint:
        image: 'stoplight/spectral'
        # cf. https://docs.stoplight.io/docs/spectral/9ffa04e052cc1-spectral-cli/
        volumes:
            - '${TOP_LEVEL_DIR}/:/tmp'
        working_dir: '/tmp'
        command: lint ${OAS_YAML} --ruleset ${SCRIPT_DIRECTORY}/spectral.yaml

    # test
    npm:
        image: 'node:latest'
        stdin_open: true
        tty: true
        volumes:
            - '${TOP_LEVEL_DIR}/:/app'
        working_dir: '/app'
        entrypoint: ['npm']
